# default_language_version:
#     python: python3.7
repos:
-   repo: https://github.com/python/black
    rev: 24.4.2
    hooks:
    - id: black

-   repo: https://github.com/codespell-project/codespell
    rev: v2.3.0
    hooks:
    - id: codespell
      additional_dependencies:
        - tomli

-   repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.4.2
    hooks:
    - id: ruff
      # args: [--fix, --exit-non-zero-on-fix]

-   repo: https://github.com/abravalheri/validate-pyproject
    rev: v0.23
    hooks:
    - id: validate-pyproject

-   repo: https://github.com/tox-dev/pyproject-fmt
    rev: v2.5.0
    hooks:
    - id: pyproject-fmt
