name: Release

on:
  push:
    tags:
      - '*'

jobs:
  pypi-publish:
    if: startsWith(github.ref, 'refs/tags')
    name: Upload release to PyPI
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/web.py-update
    permissions:
      id-token: write  # IMPORTANT: this permission is mandatory for trusted publishing
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
    - name: Build
      run: |
        python -m pip install setuptools build wheel
        python -m build .
    - name: Publish package distributions to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
